FROM mpsamurai/neochi-dev-base:20190424-raspbian

COPY ./requirements.txt /tmp/requirements.txt
RUN pip3 install --no-cache-dir -r /tmp/requirements.txt && rm /tmp/requirements.txt

COPY ./entrypoint.sh /usr/local/bin
ENTRYPOINT ["entrypoint.sh"]

WORKDIR /code
COPY ./src /code

CMD ["python", "kinesis/kinesis.py"]